### ISSUE TITLE
'Authors' menu item

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre.github.io#341]
On maplibre.org somehow an 'Authors' menu item popped up

<img width="847" alt="image" src="https://github.com/user-attachments/assets/792ac6ed-9088-4b39-a910-d258639e347a">

I don't see it when I build it locally 🤔

**Comment by CommanderStorm** [comment]
The reason for this top level icon is as far as I read the config and the docs that 

https://github.com/maplibre/maplibre.github.io/blob/ab95bb0512addf96bb5600a988a22d8e7010fd2e/config.toml#L5
https://gohugo.io/content-management/menus/#define-automatically

is used => we use the top level here:
![image](https://github.com/user-attachments/assets/fc8d131a-f89a-4c8d-8a86-4836660e0660)

Now the fun part:
`authors` does not have a dedicated list page => using the defaults

My hypotheis is that hugo switched their defaults sometime since the last dependency bump.

I see two options:
- update hugo
- add a list page for `authors` which disables this behaviour.

**Comment by CommanderStorm** [comment]
https://github.com/gohugoio/hugo/pull/12403
